version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
      timezone: 'Europe/Lisbon'
      day: 'sunday'
      time: '23:00'
