name: Dependabot auto-merge

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  auto-merge:
    name: 'Auto-Merge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor, patch
          github-token: ${{ secrets.GITHUB_TOKEN }}
