on:
  pull_request:

jobs:
  dependabot:
    name: "Dependabot"
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}} # Detect that the  PR author is dependabot
    steps:
    - name: Fetch Metadata from Dependabot PRs
    id: dependabot-metadata
      uses: dependabot/fetch-metadata@v1.3.5
      with:
        alert-lookup: true
        compat-lookup: true
        github-token: "${{ secrets.PAT_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
